-- Superseded by V1.11__seed_features_and_plans.sql.
-- This repeatable migration is intentionally empty.
-- Feature and plan seed data is now a versioned migration
-- that runs once and goes to production.
