-- Spec references: A-0021.
--
-- R__seed_reference_data.sql — Core Reference Data Seed (repeatable)
--
-- Seeds system-wide reference data required by all tenants:
--   - country         — ISO country list (FK target for entity)
--   - entity_class    — contact classification types
--   - trans_type      — journal transaction type codes
--   - language        — supported UI languages
--   - account_link_description — valid account link type codes
--   - defaults        — system settings / configuration
--
-- Idempotent: uses ON CONFLICT DO NOTHING for all inserts.
-- Repeatable (R__) so it can be re-run after schema changes without version bumps.

-- ---------------------------------------------------------------------------
-- country
-- ---------------------------------------------------------------------------

INSERT INTO country (id, name, short_name) VALUES
    (1,   'Ascension Island',                'AC'),
    (2,   'Andorra',                         'AD'),
    (3,   'United Arab Emirates',            'AE'),
    (4,   'Afghanistan',                     'AF'),
    (5,   'Antigua and Barbuda',             'AG'),
    (6,   'Anguilla',                        'AI'),
    (7,   'Albania',                         'AL'),
    (8,   'Armenia',                         'AM'),
    (9,   'Netherlands Antilles',            'AN'),
    (10,  'Angola',                          'AO'),
    (11,  'Antarctica',                      'AQ'),
    (12,  'Argentina',                       'AR'),
    (13,  'American Samoa',                  'AS'),
    (14,  'Austria',                         'AT'),
    (15,  'Australia',                       'AU'),
    (16,  'Aruba',                           'AW'),
    (17,  'Aland Islands',                   'AX'),
    (18,  'Azerbaijan',                      'AZ'),
    (19,  'Bosnia and Herzegovina',          'BA'),
    (20,  'Barbados',                        'BB'),
    (21,  'Bangladesh',                      'BD'),
    (22,  'Belgium',                         'BE'),
    (23,  'Burkina Faso',                    'BF'),
    (24,  'Bulgaria',                        'BG'),
    (25,  'Bahrain',                         'BH'),
    (26,  'Burundi',                         'BI'),
    (27,  'Benin',                           'BJ'),
    (28,  'Bermuda',                         'BM'),
    (29,  'Brunei Darussalam',               'BN'),
    (30,  'Bolivia',                         'BO'),
    (31,  'Brazil',                          'BR'),
    (32,  'Bahamas',                         'BS'),
    (33,  'Bhutan',                          'BT'),
    (34,  'Bouvet Island',                   'BV'),
    (35,  'Botswana',                        'BW'),
    (36,  'Belarus',                         'BY'),
    (37,  'Belize',                          'BZ'),
    (38,  'Canada',                          'CA'),
    (39,  'Cocos (Keeling) Islands',         'CC'),
    (40,  'Congo, Democratic Republic',      'CD'),
    (41,  'Central African Republic',        'CF'),
    (42,  'Congo',                           'CG'),
    (43,  'Switzerland',                     'CH'),
    (44,  'Cote D''Ivoire (Ivory Coast)',    'CI'),
    (45,  'Cook Islands',                    'CK'),
    (46,  'Chile',                           'CL'),
    (47,  'Cameroon',                        'CM'),
    (48,  'China',                           'CN'),
    (49,  'Colombia',                        'CO'),
    (50,  'Costa Rica',                      'CR'),
    (51,  'Czechoslovakia (former)',         'CS'),
    (52,  'Cuba',                            'CU'),
    (53,  'Cape Verde',                      'CV'),
    (54,  'Christmas Island',               'CX'),
    (55,  'Cyprus',                          'CY'),
    (56,  'Czech Republic',                  'CZ'),
    (57,  'Germany',                         'DE'),
    (58,  'Djibouti',                        'DJ'),
    (59,  'Denmark',                         'DK'),
    (60,  'Dominica',                        'DM'),
    (61,  'Dominican Republic',              'DO'),
    (62,  'Algeria',                         'DZ'),
    (63,  'Ecuador',                         'EC'),
    (64,  'Estonia',                         'EE'),
    (65,  'Egypt',                           'EG'),
    (66,  'Western Sahara',                  'EH'),
    (67,  'Eritrea',                         'ER'),
    (68,  'Spain',                           'ES'),
    (69,  'Ethiopia',                        'ET'),
    (70,  'Finland',                         'FI'),
    (71,  'Fiji',                            'FJ'),
    (72,  'Falkland Islands (Malvinas)',     'FK'),
    (73,  'Micronesia',                      'FM'),
    (74,  'Faroe Islands',                   'FO'),
    (75,  'France',                          'FR'),
    (76,  'France, Metropolitan',            'FX'),
    (77,  'Gabon',                           'GA'),
    (78,  'Great Britain (UK)',              'GB'),
    (79,  'Grenada',                         'GD'),
    (80,  'Georgia',                         'GE'),
    (81,  'French Guiana',                   'GF'),
    (82,  'Ghana',                           'GH'),
    (83,  'Gibraltar',                       'GI'),
    (84,  'Greenland',                       'GL'),
    (85,  'Gambia',                          'GM'),
    (86,  'Guinea',                          'GN'),
    (87,  'Guadeloupe',                      'GP'),
    (88,  'Equatorial Guinea',               'GQ'),
    (89,  'Greece',                          'GR'),
    (90,  'S. Georgia and S. Sandwich Isls.','GS'),
    (91,  'Guatemala',                       'GT'),
    (92,  'Guam',                            'GU'),
    (93,  'Guinea-Bissau',                   'GW'),
    (94,  'Guyana',                          'GY'),
    (95,  'Hong Kong',                       'HK'),
    (96,  'Heard and McDonald Islands',      'HM'),
    (97,  'Honduras',                        'HN'),
    (98,  'Croatia (Hrvatska)',              'HR'),
    (99,  'Haiti',                           'HT'),
    (100, 'Hungary',                         'HU'),
    (101, 'Indonesia',                       'ID'),
    (102, 'Ireland',                         'IE'),
    (103, 'Israel',                          'IL'),
    (104, 'Isle of Man',                     'IM'),
    (105, 'India',                           'IN'),
    (106, 'British Indian Ocean Territory',  'IO'),
    (107, 'Iraq',                            'IQ'),
    (108, 'Iran',                            'IR'),
    (109, 'Iceland',                         'IS'),
    (110, 'Italy',                           'IT'),
    (111, 'Jersey',                          'JE'),
    (112, 'Jamaica',                         'JM'),
    (113, 'Jordan',                          'JO'),
    (114, 'Japan',                           'JP'),
    (115, 'Kenya',                           'KE'),
    (116, 'Kyrgyzstan',                      'KG'),
    (117, 'Cambodia',                        'KH'),
    (118, 'Kiribati',                        'KI'),
    (119, 'Comoros',                         'KM'),
    (120, 'Saint Kitts and Nevis',           'KN'),
    (121, 'Korea (North)',                   'KP'),
    (122, 'Korea (South)',                   'KR'),
    (123, 'Kuwait',                          'KW'),
    (124, 'Cayman Islands',                  'KY'),
    (125, 'Kazakhstan',                      'KZ'),
    (126, 'Laos',                            'LA'),
    (127, 'Lebanon',                         'LB'),
    (128, 'Saint Lucia',                     'LC'),
    (129, 'Liechtenstein',                   'LI'),
    (130, 'Sri Lanka',                       'LK'),
    (131, 'Liberia',                         'LR'),
    (132, 'Lesotho',                         'LS'),
    (133, 'Lithuania',                       'LT'),
    (134, 'Luxembourg',                      'LU'),
    (135, 'Latvia',                          'LV'),
    (136, 'Libya',                           'LY'),
    (137, 'Morocco',                         'MA'),
    (138, 'Monaco',                          'MC'),
    (139, 'Moldova',                         'MD'),
    (140, 'Madagascar',                      'MG'),
    (141, 'Marshall Islands',               'MH'),
    (142, 'F.Y.R.O.M. (Macedonia)',          'MK'),
    (143, 'Mali',                            'ML'),
    (144, 'Myanmar',                         'MM'),
    (145, 'Mongolia',                        'MN'),
    (146, 'Macau',                           'MO'),
    (147, 'Northern Mariana Islands',        'MP'),
    (148, 'Martinique',                      'MQ'),
    (149, 'Mauritania',                      'MR'),
    (150, 'Montserrat',                      'MS'),
    (151, 'Malta',                           'MT'),
    (152, 'Mauritius',                       'MU'),
    (153, 'Maldives',                        'MV'),
    (154, 'Malawi',                          'MW'),
    (155, 'Mexico',                          'MX'),
    (156, 'Malaysia',                        'MY'),
    (157, 'Mozambique',                      'MZ'),
    (158, 'Namibia',                         'NA'),
    (159, 'New Caledonia',                   'NC'),
    (160, 'Niger',                           'NE'),
    (161, 'Norfolk Island',                  'NF'),
    (162, 'Nigeria',                         'NG'),
    (163, 'Nicaragua',                       'NI'),
    (164, 'Netherlands',                     'NL'),
    (165, 'Norway',                          'NO'),
    (166, 'Nepal',                           'NP'),
    (167, 'Nauru',                           'NR'),
    (168, 'Neutral Zone',                    'NT'),
    (169, 'Niue',                            'NU'),
    (170, 'New Zealand (Aotearoa)',          'NZ'),
    (171, 'Oman',                            'OM'),
    (172, 'Panama',                          'PA'),
    (173, 'Peru',                            'PE'),
    (174, 'French Polynesia',               'PF'),
    (175, 'Papua New Guinea',               'PG'),
    (176, 'Philippines',                    'PH'),
    (177, 'Pakistan',                        'PK'),
    (178, 'Poland',                          'PL'),
    (179, 'St. Pierre and Miquelon',        'PM'),
    (180, 'Pitcairn',                        'PN'),
    (181, 'Puerto Rico',                     'PR'),
    (182, 'Palestinian Territory, Occupied', 'PS'),
    (183, 'Portugal',                        'PT'),
    (184, 'Palau',                           'PW'),
    (185, 'Paraguay',                        'PY'),
    (186, 'Qatar',                           'QA'),
    (187, 'Reunion',                         'RE'),
    (188, 'Romania',                         'RO'),
    (189, 'Serbia',                          'RS'),
    (190, 'Russian Federation',             'RU'),
    (191, 'Rwanda',                          'RW'),
    (192, 'Saudi Arabia',                    'SA'),
    (193, 'Solomon Islands',                 'SB'),
    (194, 'Seychelles',                      'SC'),
    (195, 'Sudan',                           'SD'),
    (196, 'Sweden',                          'SE'),
    (197, 'Singapore',                       'SG'),
    (198, 'St. Helena',                      'SH'),
    (199, 'Slovenia',                        'SI'),
    (200, 'Svalbard & Jan Mayen Islands',    'SJ'),
    (201, 'Slovak Republic',                 'SK'),
    (202, 'Sierra Leone',                    'SL'),
    (203, 'San Marino',                      'SM'),
    (204, 'Senegal',                         'SN'),
    (205, 'Somalia',                         'SO'),
    (206, 'Suriname',                        'SR'),
    (207, 'Sao Tome and Principe',          'ST'),
    (208, 'USSR (former)',                   'SU'),
    (209, 'El Salvador',                     'SV'),
    (210, 'Syria',                           'SY'),
    (211, 'Swaziland',                       'SZ'),
    (212, 'Turks and Caicos Islands',        'TC'),
    (213, 'Chad',                            'TD'),
    (214, 'French Southern Territories',    'TF'),
    (215, 'Togo',                            'TG'),
    (216, 'Thailand',                        'TH'),
    (217, 'Tajikistan',                      'TJ'),
    (218, 'Tokelau',                         'TK'),
    (219, 'Turkmenistan',                    'TM'),
    (220, 'Tunisia',                         'TN'),
    (221, 'Tonga',                           'TO'),
    (222, 'East Timor',                      'TP'),
    (223, 'Turkey',                          'TR'),
    (224, 'Trinidad and Tobago',            'TT'),
    (225, 'Tuvalu',                          'TV'),
    (226, 'Taiwan',                          'TW'),
    (227, 'Tanzania',                        'TZ'),
    (228, 'Ukraine',                         'UA'),
    (229, 'Uganda',                          'UG'),
    (230, 'United Kingdom',                  'UK'),
    (231, 'US Minor Outlying Islands',       'UM'),
    (232, 'United States',                   'US'),
    (233, 'Uruguay',                         'UY'),
    (234, 'Uzbekistan',                      'UZ'),
    (235, 'Vatican City State (Holy See)',   'VA'),
    (236, 'Saint Vincent & the Grenadines', 'VC'),
    (237, 'Venezuela',                       'VE'),
    (238, 'British Virgin Islands',          'VG'),
    (239, 'Virgin Islands (U.S.)',           'VI'),
    (240, 'Viet Nam',                        'VN'),
    (241, 'Vanuatu',                         'VU'),
    (242, 'Wallis and Futuna Islands',       'WF'),
    (243, 'Samoa',                           'WS'),
    (244, 'Yemen',                           'YE'),
    (245, 'Mayotte',                         'YT'),
    (246, 'Yugoslavia (former)',             'YU'),
    (247, 'South Africa',                    'ZA'),
    (248, 'Zambia',                          'ZM'),
    (249, 'Zaire',                           'ZR'),
    (250, 'Zimbabwe',                        'ZW'),
    (251, 'St. Barthelemy',                  'BL'),
    (252, 'Caribbean Netherlands',           'BQ'),
    (253, 'Curacao',                         'CW'),
    (254, 'Diego Garcia',                    'DG'),
    (255, 'Ceuta & Melilla',                 'EA'),
    (256, 'Guernsey',                        'GG'),
    (257, 'Canary Islands',                  'IC'),
    (258, 'Montenegro',                      'ME'),
    (259, 'St. Martin',                      'MF'),
    (260, 'South Sudan',                     'SS'),
    (261, 'Sint Maarten',                    'SX'),
    (262, 'Timor-Leste',                     'TL'),
    (263, 'Kosovo',                          'XK')
ON CONFLICT (id) DO NOTHING;

-- Advance the country sequence past the seeded IDs so new inserts don't collide.
SELECT setval(
    pg_get_serial_sequence('country', 'id'),
    GREATEST((SELECT MAX(id) FROM country), 263)
);

-- ---------------------------------------------------------------------------
-- entity_class
-- ---------------------------------------------------------------------------

INSERT INTO entity_class (id, class, active) VALUES
    (1,  'Vendor',         true),
    (2,  'Customer',       true),
    (3,  'Employee',       true),
    (4,  'Contact',        true),
    (5,  'Lead',           true),
    (6,  'Referral',       true),
    (7,  'Hot Lead',       true),
    (8,  'Cold Lead',      true),
    (9,  'Sub-contractor', true),
    (10, 'Robot',          true)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('entity_class', 'id'),
    GREATEST((SELECT MAX(id) FROM entity_class), 10)
);

-- ---------------------------------------------------------------------------
-- trans_type
-- ---------------------------------------------------------------------------

INSERT INTO trans_type (code, description) VALUES
    ('ap', 'The transaction is a regular Accounts Payable item'),
    ('ar', 'The transaction is a regular Accounts Receivable item'),
    ('as', 'The transaction is generated by stocking of an assembly.'),
    ('fa', 'The transaction is generated by fixed assets depreciation'),
    ('fd', 'The transaction is generated by fixed assets disposal'),
    ('gl', 'The transaction is a regular (manually entered) journal.'),
    ('ia', 'The transaction is generated by inventory adjustment.'),
    ('op', 'The transaction is generated by an overpayment'),
    ('up', 'The transaction is generated by a software upgrade'),
    ('ye', 'The transaction is generated by Year-End processes')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- language
-- ---------------------------------------------------------------------------

INSERT INTO language (code, description) VALUES
    ('ar_EG', 'Arabic (Egypt)'),
    ('bg',    'Bulgarian'),
    ('ca',    'Catalan'),
    ('cs',    'Czech'),
    ('da',    'Danish'),
    ('de',    'German'),
    ('de_CH', 'German (Switzerland)'),
    ('el',    'Greek'),
    ('en',    'English'),
    ('en_CA', 'English (Canada)'),
    ('en_GB', 'English (UK)'),
    ('en_US', 'English (US)'),
    ('es',    'Spanish'),
    ('es_AR', 'Spanish (Argentina)'),
    ('es_CO', 'Spanish (Colombia)'),
    ('es_EC', 'Spanish (Ecuador)'),
    ('es_MX', 'Spanish (Mexico)'),
    ('es_PA', 'Spanish (Panama)'),
    ('es_PY', 'Spanish (Paraguay)'),
    ('es_VE', 'Spanish (Venezuela)'),
    ('et',    'Estonian'),
    ('fi',    'Finnish'),
    ('fr',    'French'),
    ('fr_BE', 'French (Belgium)'),
    ('fr_CA', 'French (Canada)'),
    ('hu',    'Hungarian'),
    ('id',    'Indonesian'),
    ('is',    'Icelandic'),
    ('it',    'Italian'),
    ('lt',    'Latvian'),
    ('ms_MY', 'Malay'),
    ('nb',    'Norwegian'),
    ('nl',    'Dutch'),
    ('nl_BE', 'Dutch (Belgium)'),
    ('pl',    'Polish'),
    ('pt',    'Portuguese'),
    ('pt_BR', 'Portuguese (Brazil)'),
    ('ru',    'Russian'),
    ('sv',    'Swedish'),
    ('tr',    'Turkish'),
    ('uk',    'Ukranian'),
    ('zh_CN', 'Chinese (China)'),
    ('zh_TW', 'Chinese (Taiwan)')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- account_link_description
-- ---------------------------------------------------------------------------

-- description: link type code, summary: true = this is a summary/control account link,
-- custom: true = user-defined link type (all standard types are false)
INSERT INTO account_link_description (description, summary, custom) VALUES
    ('AP',             true,  false),
    ('AP_amount',      false, false),
    ('AP_discount',    false, false),
    ('AP_expense',     false, false),
    ('AP_overpayment', false, false),
    ('AP_paid',        false, false),
    ('AP_tax',         false, false),
    ('AR',             true,  false),
    ('AR_amount',      false, false),
    ('AR_discount',    false, false),
    ('AR_overpayment', false, false),
    ('AR_paid',        false, false),
    ('AR_tax',         false, false),
    ('Asset_Dep',      false, false),
    ('asset_expense',  false, false),
    ('asset_gain',     false, false),
    ('asset_loss',     false, false),
    ('Fixed_Asset',    false, false),
    ('IC',             true,  false),
    ('IC_cogs',        false, false),
    ('IC_expense',     false, false),
    ('IC_income',      false, false),
    ('IC_returns',     false, false),
    ('IC_sale',        false, false),
    ('IC_tax',         false, false),
    ('IC_taxpart',     false, false),
    ('IC_taxservice',  false, false)
ON CONFLICT (description) DO NOTHING;

-- ---------------------------------------------------------------------------
-- defaults  (system settings)
-- ---------------------------------------------------------------------------

INSERT INTO defaults (setting_key, value) VALUES
    ('audittrail',         '0'),
    ('batch_cc',           'B-11111'),
    ('businessnumber',     '1'),
    ('check_max_invoices', '45'),
    ('check_prefix',       'CK'),
    ('curr',               'AUD'),
    ('customernumber',     '1'),
    ('decimal_places',     '2'),
    ('disable_back',       '0'),
    ('dojo_theme',         'claro'),
    ('employeenumber',     '1'),
    ('entity_control',     'A-00030'),
    ('expense_accno_id',   '57'),
    ('fxgain_accno_id',    '54'),
    ('fxloss_accno_id',    '100'),
    ('glnumber',           '1'),
    ('income_accno_id',    '47'),
    ('inventory_accno_id', '12'),
    ('lotnumber',          '1'),
    ('module_load_ok',     'yes'),
    ('partnumber',         '1'),
    ('paynumber',          '1'),
    ('ponumber',           '1'),
    ('projectnumber',      '1'),
    ('rcptnumber',         '1'),
    ('rfqnumber',          '1'),
    ('separate_duties',    '1'),
    ('sinumber',           '1'),
    ('sonumber',           '1'),
    ('sqnumber',           '1'),
    ('timeout',            '90 minutes'),
    ('vclimit',            '9999'),
    ('vendornumber',       '1'),
    ('version',            '1.14.0-dev'),
    ('vinumber',           '1'),
    ('weightunit',         'kg')
ON CONFLICT (setting_key) DO NOTHING;
