-- Spec references: A-0021.
--
-- R__seed_chart_of_accounts_au.sql — Australian Chart of Accounts Seed (repeatable)
--
-- Seeds the standard Australian General Chart of Accounts:
--   1. account_heading — section headings (groups accounts into categories)
--   2. account         — individual GL accounts
--   3. account_link    — links accounts to functional roles (AR, AP, IC, etc.)
--
-- Idempotent: uses ON CONFLICT DO NOTHING for all inserts.
-- Sequences are advanced after inserts so subsequent manual/app inserts
-- receive correct non-colliding IDs.
--
-- Repeatable (R__) so it re-runs safely on clean environments or
-- after structural schema changes without version bumps.
--
-- Structure:
--   1000–1499  Current Assets
--   1500–1799  Inventory Assets
--   1800–1999  Non-Current Assets
--   2000–2699  Current Liabilities
--   2700–2999  Non-Current Liabilities
--   3000–3999  Equity
--   4000–4399  Sales Revenue
--   4400–4999  Other Revenue
--   5000–5499  Cost of Goods Sold
--   5500–5999  Payroll Expenses
--   6000–6999  Operating Expenses

-- ---------------------------------------------------------------------------
-- account_heading
-- ---------------------------------------------------------------------------
-- Inserts use explicit IDs (GENERATED BY DEFAULT AS IDENTITY allows this).
-- ON CONFLICT on accno (the PK) ensures idempotency.

INSERT INTO account_heading (id, accno, description, category, parent_id) VALUES
    (1,  '1000', 'CURRENT ASSETS',        NULL, NULL),
    (2,  '1500', 'INVENTORY ASSETS',      NULL, NULL),
    (3,  '1800', 'NON-CURRENT ASSETS',    NULL, NULL),
    (4,  '2000', 'CURRENT LIABILITIES',   NULL, NULL),
    (5,  '2700', 'NON-CURRENT LIABILITIES', NULL, NULL),
    (6,  '3000', 'EQUITY',                NULL, NULL),
    (7,  '4000', 'SALES REVENUE',         NULL, NULL),
    (8,  '4400', 'OTHER REVENUE',         NULL, NULL),
    (9,  '5000', 'COST OF GOODS SOLD',    NULL, NULL),
    (10, '5500', 'PAYROLL EXPENSES',      NULL, NULL),
    (11, '6000', 'OPERATING EXPENSES',    NULL, NULL)
ON CONFLICT (accno) DO NOTHING;

-- Advance the account_heading identity sequence past the seeded IDs.
SELECT setval(
    pg_get_serial_sequence('account_heading', 'id'),
    GREATEST((SELECT MAX(id) FROM account_heading), 11)
);

-- ---------------------------------------------------------------------------
-- account
-- ---------------------------------------------------------------------------
-- heading column is the integer FK to account_heading.id.
-- Inserts resolve heading by the known account_heading IDs seeded above.
-- ON CONFLICT on accno (the PK) ensures idempotency.

INSERT INTO account (id, accno, description, is_temp, category, gifi_accno, heading, contra, tax, obsolete, heading_negative_balance, open_item_managed) VALUES
    -- Current Assets (heading 1 = 1000)
    (1,  '1010', 'Cheque Account',                              false, 'A', NULL, 1,  false, false, false, NULL, false),
    (2,  '1020', 'Savings Account',                             false, 'A', NULL, 1,  false, false, false, NULL, false),
    (3,  '1030', 'Petty Cash',                                  false, 'A', NULL, 1,  false, false, false, NULL, false),
    (4,  '1040', 'Undeposited Funds',                           false, 'A', NULL, 1,  false, false, false, NULL, false),
    (5,  '1100', 'Accounts Receivable',                         false, 'A', NULL, 1,  false, false, false, NULL, true),
    (6,  '1110', 'Allowance for Doubtful Debts',                false, 'A', NULL, 1,  true,  false, false, NULL, false),
    (7,  '1200', 'GST Paid',                                    false, 'A', NULL, 1,  false, true,  false, NULL, false),
    (8,  '1210', 'GST Clearing',                                false, 'A', NULL, 1,  false, false, false, NULL, false),
    (9,  '1300', 'Prepaid Expenses',                            false, 'A', NULL, 1,  false, false, false, NULL, false),
    (10, '1310', 'Prepaid Insurance',                           false, 'A', NULL, 1,  false, false, false, NULL, false),
    (11, '1400', 'Short Term Investments',                      false, 'A', NULL, 1,  false, false, false, NULL, false),
    -- Inventory Assets (heading 2 = 1500)
    (12, '1510', 'Inventory',                                   false, 'A', NULL, 2,  false, false, false, NULL, false),
    (13, '1520', 'Inventory - Work in Progress',                false, 'A', NULL, 2,  false, false, false, NULL, false),
    -- Non-Current Assets (heading 3 = 1800)
    (14, '1810', 'Land',                                        false, 'A', NULL, 3,  false, false, false, NULL, false),
    (15, '1820', 'Buildings',                                   false, 'A', NULL, 3,  false, false, false, NULL, false),
    (16, '1825', 'Accum. Depreciation - Buildings',             false, 'A', NULL, 3,  true,  false, false, NULL, false),
    (17, '1830', 'Office Furniture & Equipment',                false, 'A', NULL, 3,  false, false, false, NULL, false),
    (18, '1835', 'Accum. Depreciation - Furniture & Equipment', false, 'A', NULL, 3,  true,  false, false, NULL, false),
    (19, '1840', 'Motor Vehicles',                              false, 'A', NULL, 3,  false, false, false, NULL, false),
    (20, '1845', 'Accum. Depreciation - Motor Vehicles',        false, 'A', NULL, 3,  true,  false, false, NULL, false),
    (21, '1850', 'Computer Equipment',                          false, 'A', NULL, 3,  false, false, false, NULL, false),
    (22, '1855', 'Accum. Depreciation - Computer Equipment',    false, 'A', NULL, 3,  true,  false, false, NULL, false),
    (23, '1860', 'Plant & Machinery',                           false, 'A', NULL, 3,  false, false, false, NULL, false),
    (24, '1865', 'Accum. Depreciation - Plant & Machinery',     false, 'A', NULL, 3,  true,  false, false, NULL, false),
    -- Current Liabilities (heading 4 = 2000)
    (25, '2100', 'Accounts Payable',                            false, 'L', NULL, 4,  false, false, false, NULL, true),
    (26, '2200', 'GST Collected',                               false, 'L', NULL, 4,  false, true,  false, NULL, false),
    (27, '2210', 'PAYG Withholding Payable',                    false, 'L', NULL, 4,  false, false, false, NULL, false),
    (28, '2220', 'PAYG Income Instalment Payable',              false, 'L', NULL, 4,  false, false, false, NULL, false),
    (29, '2230', 'Superannuation Payable',                      false, 'L', NULL, 4,  false, false, false, NULL, false),
    (30, '2240', 'BAS Liability',                               false, 'L', NULL, 4,  false, false, false, NULL, false),
    (31, '2300', 'Accrued Wages',                               false, 'L', NULL, 4,  false, false, false, NULL, false),
    (32, '2310', 'Accrued Annual Leave',                        false, 'L', NULL, 4,  false, false, false, NULL, false),
    (33, '2320', 'Accrued Long Service Leave',                  false, 'L', NULL, 4,  false, false, false, NULL, false),
    (34, '2330', 'Accrued Personal/Sick Leave',                 false, 'L', NULL, 4,  false, false, false, NULL, false),
    (35, '2400', 'Credit Cards Payable',                        false, 'L', NULL, 4,  false, false, false, NULL, false),
    (36, '2500', 'Provision for Income Tax',                    false, 'L', NULL, 4,  false, false, false, NULL, false),
    (37, '2600', 'Rounding',                                    false, 'L', NULL, 4,  false, false, false, NULL, false),
    -- Non-Current Liabilities (heading 5 = 2700)
    (38, '2710', 'Bank Loans',                                  false, 'L', NULL, 5,  false, false, false, NULL, false),
    (39, '2720', 'Hire Purchase Liability',                     false, 'L', NULL, 5,  false, false, false, NULL, false),
    (40, '2730', 'Director Loans',                              false, 'L', NULL, 5,  false, false, false, NULL, false),
    (41, '2740', 'Shareholder Loans',                           false, 'L', NULL, 5,  false, false, false, NULL, false),
    -- Equity (heading 6 = 3000)
    (42, '3100', 'Share Capital',                               false, 'Q', NULL, 6,  false, false, false, NULL, false),
    (43, '3200', 'Retained Earnings',                           false, 'Q', NULL, 6,  false, false, false, NULL, false),
    (44, '3300', 'Current Year Earnings',                       false, 'Q', NULL, 6,  false, false, false, NULL, false),
    (45, '3400', 'Drawings',                                    false, 'Q', NULL, 6,  true,  false, false, NULL, false),
    (46, '3500', 'Owner Contributions',                         false, 'Q', NULL, 6,  false, false, false, NULL, false),
    -- Sales Revenue (heading 7 = 4000)
    (47, '4010', 'Sales - General',                             false, 'I', NULL, 7,  false, false, false, NULL, false),
    (48, '4020', 'Sales - Services',                            false, 'I', NULL, 7,  false, false, false, NULL, false),
    (49, '4030', 'Sales - Export (GST-Free)',                   false, 'I', NULL, 7,  false, false, false, NULL, false),
    -- Other Revenue (heading 8 = 4400)
    (50, '4410', 'Interest Received',                           false, 'I', NULL, 8,  false, false, false, NULL, false),
    (51, '4420', 'Dividends Received',                          false, 'I', NULL, 8,  false, false, false, NULL, false),
    (52, '4430', 'Rental Income',                               false, 'I', NULL, 8,  false, false, false, NULL, false),
    (53, '4440', 'Gain on Disposal of Assets',                  false, 'I', NULL, 8,  false, false, false, NULL, false),
    (54, '4450', 'Foreign Exchange Gain',                       false, 'I', NULL, 8,  false, false, false, NULL, false),
    (55, '4460', 'Shipping & Handling Income',                  false, 'I', NULL, 8,  false, false, false, NULL, false),
    (56, '4900', 'Other Revenue',                               false, 'I', NULL, 8,  false, false, false, NULL, false),
    -- Cost of Goods Sold (heading 9 = 5000)
    (57, '5010', 'Purchases',                                   false, 'E', NULL, 9,  false, false, false, NULL, false),
    (58, '5020', 'Freight & Delivery',                          false, 'E', NULL, 9,  false, false, false, NULL, false),
    (59, '5030', 'Direct Labour',                               false, 'E', NULL, 9,  false, false, false, NULL, false),
    (60, '5040', 'Subcontractors',                              false, 'E', NULL, 9,  false, false, false, NULL, false),
    (61, '5050', 'Materials',                                   false, 'E', NULL, 9,  false, false, false, NULL, false),
    -- Payroll Expenses (heading 10 = 5500)
    (62, '5510', 'Wages & Salaries',                            false, 'E', NULL, 10, false, false, false, NULL, false),
    (63, '5520', 'Overtime',                                    false, 'E', NULL, 10, false, false, false, NULL, false),
    (64, '5530', 'Superannuation Expense',                      false, 'E', NULL, 10, false, false, false, NULL, false),
    (65, '5540', 'Workers Compensation',                        false, 'E', NULL, 10, false, false, false, NULL, false),
    (66, '5550', 'Payroll Tax',                                 false, 'E', NULL, 10, false, false, false, NULL, false),
    (67, '5560', 'Annual Leave Expense',                        false, 'E', NULL, 10, false, false, false, NULL, false),
    (68, '5570', 'Long Service Leave Expense',                  false, 'E', NULL, 10, false, false, false, NULL, false),
    (69, '5580', 'Personal/Sick Leave Expense',                 false, 'E', NULL, 10, false, false, false, NULL, false),
    (70, '5590', 'Staff Training',                              false, 'E', NULL, 10, false, false, false, NULL, false),
    -- Operating Expenses (heading 11 = 6000)
    (71,  '6010', 'Accounting & Audit Fees',                    false, 'E', NULL, 11, false, false, false, NULL, false),
    (72,  '6020', 'Advertising & Promotion',                    false, 'E', NULL, 11, false, false, false, NULL, false),
    (73,  '6030', 'Bad Debts',                                  false, 'E', NULL, 11, false, false, false, NULL, false),
    (74,  '6040', 'Bank Charges & Fees',                        false, 'E', NULL, 11, false, false, false, NULL, false),
    (75,  '6050', 'Cleaning',                                   false, 'E', NULL, 11, false, false, false, NULL, false),
    (76,  '6060', 'Computer Expenses',                          false, 'E', NULL, 11, false, false, false, NULL, false),
    (77,  '6070', 'Consulting & Professional Fees',             false, 'E', NULL, 11, false, false, false, NULL, false),
    (78,  '6080', 'Depreciation Expense',                       false, 'E', NULL, 11, false, false, false, NULL, false),
    (79,  '6090', 'Donations',                                  false, 'E', NULL, 11, false, false, false, NULL, false),
    (80,  '6100', 'Electricity & Gas',                          false, 'E', NULL, 11, false, false, false, NULL, false),
    (81,  '6110', 'Entertainment',                              false, 'E', NULL, 11, false, false, false, NULL, false),
    (82,  '6120', 'Fines & Penalties',                          false, 'E', NULL, 11, false, false, false, NULL, false),
    (83,  '6130', 'General Expenses',                           false, 'E', NULL, 11, false, false, false, NULL, false),
    (84,  '6140', 'Insurance',                                  false, 'E', NULL, 11, false, false, false, NULL, false),
    (85,  '6150', 'Interest Expense',                           false, 'E', NULL, 11, false, false, false, NULL, false),
    (86,  '6160', 'Legal Fees',                                 false, 'E', NULL, 11, false, false, false, NULL, false),
    (87,  '6170', 'Motor Vehicle Expenses',                     false, 'E', NULL, 11, false, false, false, NULL, false),
    (88,  '6180', 'Office Supplies',                            false, 'E', NULL, 11, false, false, false, NULL, false),
    (89,  '6190', 'Postage & Courier',                          false, 'E', NULL, 11, false, false, false, NULL, false),
    (90,  '6200', 'Printing & Stationery',                      false, 'E', NULL, 11, false, false, false, NULL, false),
    (91,  '6210', 'Rates & Levies',                             false, 'E', NULL, 11, false, false, false, NULL, false),
    (92,  '6220', 'Rent',                                       false, 'E', NULL, 11, false, false, false, NULL, false),
    (93,  '6230', 'Repairs & Maintenance',                      false, 'E', NULL, 11, false, false, false, NULL, false),
    (94,  '6240', 'Security',                                   false, 'E', NULL, 11, false, false, false, NULL, false),
    (95,  '6250', 'Software & Subscriptions',                   false, 'E', NULL, 11, false, false, false, NULL, false),
    (96,  '6260', 'Telephone & Internet',                       false, 'E', NULL, 11, false, false, false, NULL, false),
    (97,  '6270', 'Travel - Domestic',                          false, 'E', NULL, 11, false, false, false, NULL, false),
    (98,  '6280', 'Travel - International',                     false, 'E', NULL, 11, false, false, false, NULL, false),
    (99,  '6290', 'Uniforms & Protective Clothing',             false, 'E', NULL, 11, false, false, false, NULL, false),
    (100, '6300', 'Foreign Exchange Loss',                      false, 'E', NULL, 11, false, false, false, NULL, false)
ON CONFLICT (accno) DO NOTHING;

-- Advance the account identity sequence past the seeded IDs.
SELECT setval(
    pg_get_serial_sequence('account', 'id'),
    GREATEST((SELECT MAX(id) FROM account), 100)
);

-- ---------------------------------------------------------------------------
-- account_link
-- ---------------------------------------------------------------------------
-- Resolves account_id from accno via subquery — avoids hardcoding IDs and
-- handles re-runs cleanly when accounts already exist.
-- ON CONFLICT on (account_id, description) PK ensures idempotency.

INSERT INTO account_link (account_id, description)
SELECT a.id, l.description
FROM (VALUES
    -- 1010 Cheque Account
    ('1010', 'AP_paid'),
    ('1010', 'AR_paid'),
    -- 1020 Savings Account
    ('1020', 'AP_paid'),
    ('1020', 'AR_paid'),
    -- 1030 Petty Cash
    ('1030', 'AP_paid'),
    ('1030', 'AR_paid'),
    -- 1040 Undeposited Funds
    ('1040', 'AR_paid'),
    -- 1100 Accounts Receivable
    ('1100', 'AR'),
    -- 1200 GST Paid
    ('1200', 'AP_tax'),
    ('1200', 'IC_taxpart'),
    ('1200', 'IC_taxservice'),
    -- 1510 Inventory
    ('1510', 'IC'),
    -- 1810 Land
    ('1810', 'Fixed_Asset'),
    -- 1820 Buildings
    ('1820', 'Fixed_Asset'),
    -- 1825 Accum. Depreciation - Buildings
    ('1825', 'Asset_Dep'),
    -- 1830 Office Furniture & Equipment
    ('1830', 'Fixed_Asset'),
    -- 1835 Accum. Depreciation - Furniture & Equipment
    ('1835', 'Asset_Dep'),
    -- 1840 Motor Vehicles
    ('1840', 'Fixed_Asset'),
    -- 1845 Accum. Depreciation - Motor Vehicles
    ('1845', 'Asset_Dep'),
    -- 1850 Computer Equipment
    ('1850', 'Fixed_Asset'),
    -- 1855 Accum. Depreciation - Computer Equipment
    ('1855', 'Asset_Dep'),
    -- 1860 Plant & Machinery
    ('1860', 'Fixed_Asset'),
    -- 1865 Accum. Depreciation - Plant & Machinery
    ('1865', 'Asset_Dep'),
    -- 2100 Accounts Payable
    ('2100', 'AP'),
    -- 2200 GST Collected
    ('2200', 'AR_tax'),
    -- 2400 Credit Cards Payable
    ('2400', 'AP_paid'),
    -- 2730 Director Loans
    ('2730', 'AP_paid'),
    -- 2740 Shareholder Loans
    ('2740', 'AP_paid'),
    -- 4010 Sales - General
    ('4010', 'AR_amount'),
    ('4010', 'IC_income'),
    ('4010', 'IC_sale'),
    -- 4020 Sales - Services
    ('4020', 'AR_amount'),
    ('4020', 'IC_income'),
    -- 4030 Sales - Export (GST-Free)
    ('4030', 'AR_amount'),
    ('4030', 'IC_income'),
    ('4030', 'IC_sale'),
    -- 4430 Rental Income
    ('4430', 'AR_amount'),
    -- 4460 Shipping & Handling Income
    ('4460', 'IC_income'),
    -- 4900 Other Revenue
    ('4900', 'AR_amount'),
    -- 5010 Purchases
    ('5010', 'AP_amount'),
    ('5010', 'IC_cogs'),
    ('5010', 'IC_expense'),
    -- 5020 Freight & Delivery
    ('5020', 'AP_amount'),
    ('5020', 'IC_expense'),
    -- 5040 Subcontractors
    ('5040', 'AP_amount'),
    -- 5050 Materials
    ('5050', 'AP_amount'),
    ('5050', 'IC_expense'),
    -- 5590 Staff Training
    ('5590', 'AP_amount'),
    -- 6010 Accounting & Audit Fees
    ('6010', 'AP_amount'),
    -- 6020 Advertising & Promotion
    ('6020', 'AP_amount'),
    -- 6050 Cleaning
    ('6050', 'AP_amount'),
    -- 6060 Computer Expenses
    ('6060', 'AP_amount'),
    -- 6070 Consulting & Professional Fees
    ('6070', 'AP_amount'),
    -- 6080 Depreciation Expense
    ('6080', 'asset_expense'),
    -- 6100 Electricity & Gas
    ('6100', 'AP_amount'),
    -- 6130 General Expenses
    ('6130', 'AP_amount'),
    -- 6140 Insurance
    ('6140', 'AP_amount'),
    -- 6160 Legal Fees
    ('6160', 'AP_amount'),
    -- 6170 Motor Vehicle Expenses
    ('6170', 'AP_amount'),
    -- 6180 Office Supplies
    ('6180', 'AP_amount'),
    -- 6190 Postage & Courier
    ('6190', 'AP_amount'),
    -- 6200 Printing & Stationery
    ('6200', 'AP_amount'),
    -- 6220 Rent
    ('6220', 'AP_amount'),
    -- 6230 Repairs & Maintenance
    ('6230', 'AP_amount'),
    -- 6240 Security
    ('6240', 'AP_amount'),
    -- 6250 Software & Subscriptions
    ('6250', 'AP_amount'),
    -- 6260 Telephone & Internet
    ('6260', 'AP_amount'),
    -- 6290 Uniforms & Protective Clothing
    ('6290', 'AP_amount')
) AS l(accno, description)
JOIN account a ON a.accno = l.accno
ON CONFLICT (account_id, description) DO NOTHING;
