-- Spec references: A-0021.
--
-- Ledgius Core Schema — V1.00
--
-- This script establishes the foundational database schema for a Ledgius tenant.
-- It is extracted from the LedgerSMB-inherited schema, retaining only the tables
-- actively used by the Ledgius Go API and their transitive FK dependencies.
--
-- What is EXCLUDED from the original LedgerSMB database:
--   - All stored procedures and functions (LedgerSMB business logic is dead)
--   - All triggers (LedgerSMB trigger logic is dead)
--   - ~200 LedgerSMB tables not referenced by the Ledgius API
--
-- What is INCLUDED:
--   - 38 tables: core transactional, reference/lookup, and auth tables
--   - All sequences (identity columns)
--   - All primary keys, unique constraints, check constraints
--   - All foreign keys (self-contained — no external table references)
--   - All indexes
--   - entity_control_seq replacing the defunct public.setting_increment() call
--
-- Tables included:
--   account_heading, account, account_link, account_link_description,
--   entity, entity_class, entity_credit_account, entity_bank_account,
--   entity_employee, company,
--   transactions, trans_type, acc_trans, gl, ar, ap,
--   open_item, invoice, currency,
--   cr_report, cr_report_line,
--   country, language, location, location_class,
--   business, sic, parts, partsgroup,
--   salutation, person,
--   voucher, batch, batch_class,
--   workflow, gifi, country_tax_form,
--   pricegroup, defaults, lsmb_sequence,
--   session, users
--

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Sequence: entity_control_seq
-- Replaces the defunct public.setting_increment('entity_control') function call
-- used as the DEFAULT on entity.control_code.
-- ---------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS entity_control_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- ---------------------------------------------------------------------------
-- Reference / lookup tables (no inbound FKs to other tables in this script)
-- ---------------------------------------------------------------------------

CREATE TABLE account_heading (
    id integer NOT NULL,
    accno text NOT NULL,
    parent_id integer,
    description text,
    category character(1),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT account_heading_category_check CHECK ((category = ANY (ARRAY['A'::bpchar, 'L'::bpchar, 'Q'::bpchar, 'I'::bpchar, 'E'::bpchar])))
);

ALTER TABLE account_heading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_heading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE gifi (
    accno text NOT NULL,
    description text,
    last_updated timestamp without time zone DEFAULT now() NOT NULL
);


CREATE TABLE account (
    id integer NOT NULL,
    accno text NOT NULL,
    description text,
    is_temp boolean DEFAULT false NOT NULL,
    category character(1) NOT NULL,
    gifi_accno text,
    heading integer NOT NULL,
    contra boolean DEFAULT false NOT NULL,
    tax boolean DEFAULT false NOT NULL,
    obsolete boolean DEFAULT false NOT NULL,
    heading_negative_balance integer,
    custom_attributes jsonb,
    open_item_managed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT account_category_check CHECK ((category = ANY (ARRAY['A'::bpchar, 'L'::bpchar, 'Q'::bpchar, 'I'::bpchar, 'E'::bpchar]))),
    CONSTRAINT account_heading_neg_balance CHECK (((category = ANY (ARRAY['A'::bpchar, 'L'::bpchar])) OR (heading_negative_balance IS NULL)))
);

ALTER TABLE account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE account_link_description (
    description text NOT NULL,
    summary boolean NOT NULL,
    custom boolean NOT NULL
);


CREATE TABLE account_link (
    account_id integer NOT NULL,
    description text NOT NULL
);


CREATE TABLE currency (
    curr character(3) NOT NULL,
    description text
);


CREATE TABLE country (
    id integer NOT NULL,
    name text NOT NULL,
    short_name text NOT NULL,
    itu text,
    last_updated timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT country_name_check CHECK ((name ~ '[[:alnum:]_]'::text)),
    CONSTRAINT country_short_name_check CHECK ((short_name ~ '[[:alnum:]_]'::text))
);

ALTER TABLE country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME country_id_seq
    START WITH 264
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE country_tax_form (
    country_id integer NOT NULL,
    form_name text NOT NULL,
    id integer NOT NULL,
    default_reportable boolean DEFAULT false NOT NULL,
    is_accrual boolean DEFAULT false NOT NULL
);

ALTER TABLE country_tax_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME country_tax_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE language (
    code character varying(6) NOT NULL,
    description text,
    last_updated timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT language_code_check CHECK (((code)::text ~ '^[a-z]{2}(_[A-Z]{2})?$'::text))
);


CREATE TABLE location_class (
    id integer NOT NULL,
    class text NOT NULL,
    authoritative boolean NOT NULL,
    CONSTRAINT location_class_class_check CHECK ((class ~ '[[:alnum:]_]'::text))
);

ALTER TABLE location_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME location_class_id_seq
    START WITH 6
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE location (
    id integer NOT NULL,
    line_one text NOT NULL,
    line_two text,
    line_three text,
    city text NOT NULL,
    state text,
    country_id integer NOT NULL,
    mail_code text,
    CONSTRAINT location_city_check CHECK ((city ~ '[[:alnum:]_]'::text)),
    CONSTRAINT location_line_one_check CHECK ((line_one ~ '[[:alnum:]_]'::text)),
    CONSTRAINT location_mail_code_check CHECK ((mail_code ~ '[[:alnum:]_-]'::text)),
    CONSTRAINT location_state_check CHECK ((state ~ '[[:alnum:]_]'::text))
);

ALTER TABLE location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE salutation (
    id integer NOT NULL,
    salutation text NOT NULL
);

ALTER TABLE salutation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME salutation_id_seq
    START WITH 9
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE sic (
    code character varying(6) NOT NULL,
    sictype character(1),
    description text,
    last_updated timestamp without time zone DEFAULT now() NOT NULL,
    custom_attributes jsonb
);


CREATE TABLE business (
    id integer NOT NULL,
    description text,
    discount numeric,
    last_updated timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE business ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE partsgroup (
    id integer NOT NULL,
    partsgroup text,
    parent integer,
    last_updated timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE partsgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME partsgroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE parts (
    id integer NOT NULL,
    partnumber text,
    description text,
    unit character varying(5),
    listprice numeric,
    sellprice numeric,
    lastcost numeric,
    priceupdate date DEFAULT CURRENT_DATE,
    weight numeric,
    onhand numeric DEFAULT 0,
    notes text,
    makemodel boolean DEFAULT false,
    assembly boolean DEFAULT false,
    alternate boolean DEFAULT false,
    rop numeric,
    inventory_accno_id integer,
    income_accno_id integer,
    expense_accno_id integer,
    returns_accno_id integer,
    bin text,
    obsolete boolean DEFAULT false,
    bom boolean DEFAULT false,
    image text,
    drawing text,
    microfiche text,
    partsgroup_id integer,
    avgcost numeric,
    custom_attributes jsonb
);

ALTER TABLE parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE pricegroup (
    id integer NOT NULL,
    pricegroup text,
    last_updated timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE pricegroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pricegroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE defaults (
    setting_key text NOT NULL,
    value text,
    CONSTRAINT defaults_password_duration_check CHECK (((setting_key <> 'password_duration'::text) OR (value IS NULL) OR (value = ''::text) OR ((value ~ '^([0-9]+[.]?[0-9]*|[.][0-9]+)$'::text) AND ((value)::numeric > (0)::numeric) AND ((value)::numeric < (3654)::numeric))))
);


CREATE TABLE lsmb_sequence (
    label text NOT NULL,
    setting_key text NOT NULL,
    prefix text,
    suffix text,
    sequence text DEFAULT '1'::text NOT NULL,
    accept_input boolean DEFAULT true
);


CREATE TABLE trans_type (
    code character(2) NOT NULL,
    description character varying(1000)
);


-- ---------------------------------------------------------------------------
-- Entity tables
-- ---------------------------------------------------------------------------

CREATE TABLE entity_class (
    id integer NOT NULL,
    class text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT entity_class_class_check CHECK ((class ~ '[[:alnum:]_]'::text))
);

ALTER TABLE entity_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entity_class_id_seq
    START WITH 11
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- entity.control_code uses entity_control_seq (replaces defunct setting_increment call)
CREATE TABLE entity (
    id integer NOT NULL,
    name text,
    created date DEFAULT CURRENT_DATE NOT NULL,
    control_code text DEFAULT ('E-' || nextval('entity_control_seq')) NOT NULL,
    country_id integer NOT NULL,
    custom_attributes jsonb,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT entity_name_check CHECK ((name ~ '[[:alnum:]_]'::text))
);

ALTER TABLE entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE entity_employee (
    entity_id integer NOT NULL,
    startdate date DEFAULT CURRENT_DATE NOT NULL,
    enddate date,
    role character varying(20),
    ssn text,
    sales boolean DEFAULT false,
    manager_id integer,
    employeenumber character varying(32),
    dob date,
    is_manager boolean DEFAULT false
);


CREATE TABLE person (
    id integer NOT NULL,
    entity_id integer NOT NULL,
    salutation_id integer,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    created date DEFAULT CURRENT_DATE NOT NULL,
    birthdate date,
    personal_id text,
    CONSTRAINT person_first_name_check CHECK ((first_name ~ '[[:alnum:]_]'::text)),
    CONSTRAINT person_last_name_check CHECK ((last_name ~ '[[:alnum:]_]'::text))
);

ALTER TABLE person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE entity_bank_account (
    id integer NOT NULL,
    entity_id integer NOT NULL,
    bic character varying NOT NULL,
    iban character varying NOT NULL,
    remark character varying
);

ALTER TABLE entity_bank_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entity_bank_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE company (
    id integer NOT NULL,
    entity_id integer NOT NULL,
    legal_name text NOT NULL,
    tax_id text,
    sales_tax_id text,
    license_number text,
    sic_code character varying,
    created date DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT company_legal_name_check CHECK ((legal_name ~ '[[:alnum:]_]'::text))
);

ALTER TABLE company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE entity_credit_account (
    id integer NOT NULL,
    entity_id integer NOT NULL,
    entity_class integer NOT NULL,
    pay_to_name text,
    discount numeric,
    description text,
    discount_terms integer DEFAULT 0,
    discount_account_id integer,
    taxincluded boolean DEFAULT false,
    creditlimit numeric DEFAULT 0,
    terms smallint DEFAULT 0,
    meta_number character varying(32) NOT NULL,
    business_id integer,
    language_code character varying(6) DEFAULT 'en'::character varying,
    pricegroup_id integer,
    curr character(3),
    startdate date DEFAULT CURRENT_DATE,
    enddate date,
    threshold numeric DEFAULT 0,
    employee_id integer,
    primary_contact integer,
    ar_ap_account_id integer,
    cash_account_id integer,
    bank_account integer,
    taxform_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    status text DEFAULT 'active'::text NOT NULL,
    CONSTRAINT entity_credit_account_check CHECK (((ar_ap_account_id IS NOT NULL) OR (entity_id = 0))),
    CONSTRAINT entity_credit_account_entity_class_check CHECK ((entity_class = ANY (ARRAY[1, 2]))),
    CONSTRAINT entity_credit_account_req_curr CHECK (((entity_class = ANY (ARRAY[1, 2, 3])) AND (curr IS NOT NULL)))
);

ALTER TABLE entity_credit_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entity_credit_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- ---------------------------------------------------------------------------
-- Auth tables (users, session)
-- session references users; transactions.locked_by references session
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id integer NOT NULL,
    username character varying(30) NOT NULL,
    notify_password interval DEFAULT '7 days'::interval NOT NULL,
    entity_id integer NOT NULL
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE session (
    session_id integer NOT NULL,
    token character varying(32),
    last_used timestamp without time zone DEFAULT now(),
    ttl integer DEFAULT 3600 NOT NULL,
    users_id integer NOT NULL,
    notify_pasword interval DEFAULT '7 days'::interval NOT NULL,
    CONSTRAINT session_token_check CHECK ((length((token)::text) = 32))
);

ALTER TABLE session ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME session_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- ---------------------------------------------------------------------------
-- Workflow table (referenced by transactions and cr_report)
-- ---------------------------------------------------------------------------

CREATE TABLE workflow (
    workflow_id integer NOT NULL,
    type character varying(50) NOT NULL,
    state character varying(30) NOT NULL,
    last_update timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- ---------------------------------------------------------------------------
-- Transaction core tables
-- ---------------------------------------------------------------------------

CREATE TABLE transactions (
    id integer NOT NULL,
    table_name text NOT NULL,
    locked_by integer,
    approved boolean NOT NULL,
    approved_by integer,
    approved_at timestamp without time zone,
    transdate date,
    workflow_id integer,
    reversing integer,
    reference text,
    description text,
    trans_type_code character(2) NOT NULL,
    entered_by integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT transactions_table_name_check CHECK ((table_name = ANY (ARRAY['gl'::text, 'ap'::text, 'ar'::text, 'mfg_lot'::text, 'asset_report'::text, 'inventory_report'::text, 'yearend'::text, 'payment'::text]))),
    CONSTRAINT transdate_nullity CHECK (((NOT approved) OR (transdate IS NOT NULL)))
);

ALTER TABLE transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE open_item (
    id integer NOT NULL,
    item_number text NOT NULL,
    item_type character(2) NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT open_item_item_type_check CHECK (((item_type)::text = ANY (ARRAY['gl'::text, 'ar'::text, 'ap'::text, 'op'::text])))
);

ALTER TABLE open_item ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME open_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE invoice (
    id integer NOT NULL,
    trans_id integer,
    parts_id integer,
    description text,
    qty numeric,
    allocated numeric,
    sellprice numeric,
    "precision" integer,
    fxsellprice numeric,
    discount numeric,
    assemblyitem boolean DEFAULT false,
    unit character varying,
    deliverydate date,
    serialnumber text,
    vendor_sku text,
    notes text,
    CONSTRAINT invoice_allocation_constraint CHECK ((((allocated * ('-1'::integer)::numeric) >= LEAST((0)::numeric, qty)) AND ((allocated * ('-1'::integer)::numeric) <= GREATEST(qty, (0)::numeric))))
);

ALTER TABLE invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE gl (
    id integer NOT NULL,
    reference text,
    notes text
);


CREATE TABLE ar (
    trans_id integer NOT NULL,
    invnumber text,
    taxincluded boolean,
    duedate date,
    invoice boolean DEFAULT false,
    shippingpoint text,
    terms smallint DEFAULT 0,
    notes text,
    curr character(3),
    ordnumber text,
    person_id integer,
    quonumber text,
    intnotes text,
    shipvia text,
    language_code character varying(6),
    ponumber text,
    on_hold boolean DEFAULT false,
    reverse boolean DEFAULT false,
    entity_credit_account integer NOT NULL,
    force_closed boolean,
    is_return boolean DEFAULT false,
    crdate date,
    setting_sequence text,
    amount_bc numeric,
    amount_tc numeric,
    netamount_bc numeric,
    netamount_tc numeric,
    shipto integer,
    shipto_attn text,
    open_item_id integer NOT NULL,
    CONSTRAINT ar_check CHECK ((((amount_bc IS NULL) AND (curr IS NULL)) OR ((amount_bc IS NOT NULL) AND (curr IS NOT NULL))))
);


CREATE TABLE ap (
    trans_id integer NOT NULL,
    invnumber text,
    taxincluded boolean DEFAULT false,
    duedate date,
    invoice boolean DEFAULT false,
    ordnumber text,
    curr character(3),
    notes text,
    person_id integer,
    quonumber text,
    intnotes text,
    shipvia text,
    language_code character varying(6),
    ponumber text,
    shippingpoint text,
    on_hold boolean DEFAULT false,
    reverse boolean DEFAULT false,
    terms smallint DEFAULT 0,
    force_closed boolean,
    crdate date,
    is_return boolean DEFAULT false,
    entity_credit_account integer NOT NULL,
    amount_bc numeric,
    amount_tc numeric,
    netamount_bc numeric,
    netamount_tc numeric,
    shipto integer,
    shipto_attn text,
    open_item_id integer NOT NULL,
    CONSTRAINT ap_check CHECK ((((amount_bc IS NULL) AND (curr IS NULL)) OR ((amount_bc IS NOT NULL) AND (curr IS NOT NULL))))
);


-- ---------------------------------------------------------------------------
-- Batch tables (referenced by voucher)
-- ---------------------------------------------------------------------------

CREATE TABLE batch_class (
    id integer NOT NULL,
    class character varying NOT NULL
);

ALTER TABLE batch_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME batch_class_id_seq
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE batch (
    id integer NOT NULL,
    batch_class_id integer NOT NULL,
    control_code text NOT NULL,
    description text,
    default_date date NOT NULL,
    approved_on date,
    approved_by integer,
    created_by integer,
    locked_by integer,
    created_on date DEFAULT now(),
    CONSTRAINT batch_control_code_check CHECK ((length(control_code) > 0))
);

ALTER TABLE batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE voucher (
    trans_id integer NOT NULL,
    batch_id integer NOT NULL,
    id integer NOT NULL,
    batch_class integer NOT NULL
);

ALTER TABLE voucher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME voucher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE acc_trans (
    trans_id integer NOT NULL,
    chart_id integer NOT NULL,
    transdate date DEFAULT CURRENT_DATE,
    source text,
    cleared boolean DEFAULT false,
    memo text,
    invoice_id integer,
    approved boolean DEFAULT true NOT NULL,
    voucher_id integer,
    entry_id integer NOT NULL,
    amount_bc numeric NOT NULL,
    amount_tc numeric NOT NULL,
    curr character(3) NOT NULL,
    open_item_id integer,
    CONSTRAINT transdate_nullity CHECK (((NOT approved) OR (transdate IS NOT NULL)))
);

ALTER TABLE acc_trans ALTER COLUMN entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME acc_trans_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- ---------------------------------------------------------------------------
-- Bank reconciliation tables
-- ---------------------------------------------------------------------------

-- cr_report.entered_by DEFAULT replaced: defunct public.person__get_my_entity_id() -> 0
CREATE TABLE cr_report (
    id bigint NOT NULL,
    chart_id integer NOT NULL,
    their_total numeric NOT NULL,
    approved boolean DEFAULT false NOT NULL,
    submitted boolean DEFAULT false NOT NULL,
    end_date date DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    entered_by integer DEFAULT 0 NOT NULL,
    entered_username text DEFAULT SESSION_USER NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_by integer,
    approved_by integer,
    approved_username text,
    recon_fx boolean DEFAULT false,
    workflow_id bigint NOT NULL,
    CONSTRAINT cr_report_approved_submitted_check CHECK ((submitted OR (NOT approved))),
    CONSTRAINT cr_report_check CHECK (((deleted IS NOT TRUE) OR (approved IS NOT TRUE)))
);

ALTER TABLE cr_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cr_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE cr_report_line (
    id bigint NOT NULL,
    report_id integer NOT NULL,
    scn text,
    their_balance numeric,
    our_balance numeric,
    "user" integer NOT NULL,
    clear_time date,
    insert_time timestamp with time zone DEFAULT now() NOT NULL,
    trans_type text,
    post_date date,
    cleared boolean DEFAULT false NOT NULL
);

ALTER TABLE cr_report_line ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cr_report_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- ---------------------------------------------------------------------------
-- Primary keys and unique constraints
-- ---------------------------------------------------------------------------

ALTER TABLE ONLY account_heading
    ADD CONSTRAINT account_heading_id_key UNIQUE (id);

ALTER TABLE ONLY account_heading
    ADD CONSTRAINT account_heading_pkey PRIMARY KEY (accno);

ALTER TABLE ONLY account
    ADD CONSTRAINT account_id_key UNIQUE (id);

ALTER TABLE ONLY account
    ADD CONSTRAINT account_pkey PRIMARY KEY (accno);

ALTER TABLE ONLY account_link_description
    ADD CONSTRAINT account_link_description_pkey PRIMARY KEY (description);

ALTER TABLE ONLY account_link
    ADD CONSTRAINT account_link_pkey PRIMARY KEY (account_id, description);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_pkey PRIMARY KEY (trans_id);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_pkey PRIMARY KEY (trans_id);

ALTER TABLE ONLY batch_class
    ADD CONSTRAINT batch_class_id_key UNIQUE (id);

ALTER TABLE ONLY batch_class
    ADD CONSTRAINT batch_class_pkey PRIMARY KEY (class);

ALTER TABLE ONLY batch
    ADD CONSTRAINT batch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY business
    ADD CONSTRAINT business_pkey PRIMARY KEY (id);

ALTER TABLE ONLY company
    ADD CONSTRAINT company_id_key UNIQUE (id);

ALTER TABLE ONLY company
    ADD CONSTRAINT company_pkey PRIMARY KEY (entity_id, legal_name);

ALTER TABLE ONLY country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);

ALTER TABLE ONLY country_tax_form
    ADD CONSTRAINT country_tax_form_id_key UNIQUE (id);

ALTER TABLE ONLY country_tax_form
    ADD CONSTRAINT country_tax_form_pkey PRIMARY KEY (country_id, form_name);

ALTER TABLE ONLY cr_report_line
    ADD CONSTRAINT cr_report_line_pkey PRIMARY KEY (id);

ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_pkey PRIMARY KEY (id);

ALTER TABLE ONLY currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (curr);

ALTER TABLE ONLY defaults
    ADD CONSTRAINT defaults_pkey PRIMARY KEY (setting_key);

ALTER TABLE ONLY entity_bank_account
    ADD CONSTRAINT entity_bank_account_id_key UNIQUE (id);

ALTER TABLE ONLY entity_bank_account
    ADD CONSTRAINT entity_bank_account_pkey PRIMARY KEY (entity_id, bic, iban);

ALTER TABLE ONLY entity_class
    ADD CONSTRAINT entity_class_pkey PRIMARY KEY (id);

ALTER TABLE ONLY entity
    ADD CONSTRAINT entity_control_code_key UNIQUE (control_code);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_id_key UNIQUE (id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_pkey PRIMARY KEY (entity_id, meta_number, entity_class);

ALTER TABLE ONLY entity_employee
    ADD CONSTRAINT entity_employee_pkey PRIMARY KEY (entity_id);

ALTER TABLE ONLY entity
    ADD CONSTRAINT entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY gifi
    ADD CONSTRAINT gifi_pkey PRIMARY KEY (accno);

ALTER TABLE ONLY gl
    ADD CONSTRAINT gl_pkey PRIMARY KEY (id);

ALTER TABLE ONLY invoice
    ADD CONSTRAINT invoice_pkey PRIMARY KEY (id);

ALTER TABLE ONLY language
    ADD CONSTRAINT language_pkey PRIMARY KEY (code);

ALTER TABLE ONLY location_class
    ADD CONSTRAINT location_class_id_key UNIQUE (id);

ALTER TABLE ONLY location_class
    ADD CONSTRAINT location_class_pkey PRIMARY KEY (class, authoritative);

ALTER TABLE ONLY location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lsmb_sequence
    ADD CONSTRAINT lsmb_sequence_pkey PRIMARY KEY (label);

ALTER TABLE ONLY open_item
    ADD CONSTRAINT open_item_item_number_key UNIQUE (item_number);

ALTER TABLE ONLY open_item
    ADD CONSTRAINT open_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_pkey PRIMARY KEY (entry_id);

ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY partsgroup
    ADD CONSTRAINT partsgroup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY person
    ADD CONSTRAINT person_entity_id_key UNIQUE (entity_id);

ALTER TABLE ONLY person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);

ALTER TABLE ONLY pricegroup
    ADD CONSTRAINT pricegroup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY salutation
    ADD CONSTRAINT salutation_id_key UNIQUE (id);

ALTER TABLE ONLY salutation
    ADD CONSTRAINT salutation_pkey PRIMARY KEY (salutation);

ALTER TABLE ONLY session
    ADD CONSTRAINT session_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY sic
    ADD CONSTRAINT sic_pkey PRIMARY KEY (code);

ALTER TABLE ONLY trans_type
    ADD CONSTRAINT trans_type_pkey PRIMARY KEY (code);

ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_id_key UNIQUE (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);

ALTER TABLE ONLY voucher
    ADD CONSTRAINT voucher_pkey PRIMARY KEY (id);

ALTER TABLE ONLY workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (workflow_id);


-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX acc_trans_chart_id_idx ON acc_trans USING btree (chart_id);
CREATE INDEX acc_trans_invoice_id_idx ON acc_trans USING btree (invoice_id);
CREATE INDEX acc_trans_recon_idx ON acc_trans USING btree (chart_id, entry_id) WHERE (NOT cleared);
CREATE INDEX acc_trans_trans_id_idx ON acc_trans USING btree (trans_id);
CREATE INDEX acc_trans_transdate_year_idx ON acc_trans USING btree (transdate, date_part('YEAR'::text, transdate)) WHERE (transdate IS NOT NULL);
CREATE INDEX acc_trans_voucher_id_idx ON acc_trans USING btree (voucher_id);
CREATE INDEX ap_entity_credit_account_idx ON ap USING btree (entity_credit_account);
CREATE INDEX ar_entity_credit_account_idx ON ar USING btree (entity_credit_account);
CREATE UNIQUE INDEX ar_invnumber_key ON ar USING btree (invnumber) WHERE (invnumber IS NOT NULL);
CREATE UNIQUE INDEX ar_invnumber_key_p ON ar USING btree (invnumber) WHERE (invnumber IS NOT NULL);
CREATE UNIQUE INDEX country_name_idx ON country USING btree (lower(name));
CREATE INDEX entity_class_idx ON entity_class USING btree (lower(class));
CREATE UNIQUE INDEX entity_credit_ar_accno_idx_u ON entity_credit_account USING btree (meta_number) WHERE (entity_class = 2);
CREATE INDEX idx_acc_trans_open_item_id ON acc_trans USING btree (open_item_id) WHERE (open_item_id IS NOT NULL);
CREATE INDEX invoice_cogs_idx ON invoice USING btree (parts_id) WHERE (((qty + allocated) < (0)::numeric) OR ((qty + allocated) > (0)::numeric));
CREATE INDEX invoice_id_key ON invoice USING btree (id);
CREATE INDEX invoice_parts_id_idx ON invoice USING btree (parts_id);
CREATE INDEX invoice_trans_id_key ON invoice USING btree (trans_id);
CREATE UNIQUE INDEX language_code_key ON language USING btree (code);
CREATE UNIQUE INDEX lower_class_unique ON location_class USING btree (lower(class));
CREATE INDEX parts_description_key ON parts USING btree (lower(description));
CREATE INDEX parts_id_key ON parts USING btree (id);
CREATE UNIQUE INDEX parts_partnumber_index_u ON parts USING btree (partnumber) WHERE (obsolete IS FALSE);
CREATE INDEX parts_partnumber_key ON parts USING btree (lower(partnumber));
CREATE INDEX partsgroup_id_key ON partsgroup USING btree (id);
CREATE UNIQUE INDEX partsgroup_key ON partsgroup USING btree (partsgroup);
CREATE INDEX pricegroup_id_key ON pricegroup USING btree (id);
CREATE INDEX pricegroup_pricegroup_key ON pricegroup USING btree (pricegroup);
CREATE INDEX transactions_locked_by_i ON transactions USING btree (locked_by);
CREATE UNIQUE INDEX transactions_reversing_idx ON transactions USING btree (reversing) WHERE (reversing IS NOT NULL);
CREATE INDEX voucher_batch_id_idx ON voucher USING btree (batch_id);
CREATE INDEX voucher_trans_id_idx ON voucher USING btree (trans_id);


-- ---------------------------------------------------------------------------
-- Foreign key constraints
-- ---------------------------------------------------------------------------

-- account_heading
ALTER TABLE ONLY account_heading
    ADD CONSTRAINT account_heading_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES account_heading(id);

-- account
ALTER TABLE ONLY account
    ADD CONSTRAINT account_gifi_accno_fkey FOREIGN KEY (gifi_accno) REFERENCES gifi(accno);

ALTER TABLE ONLY account
    ADD CONSTRAINT account_heading_fkey FOREIGN KEY (heading) REFERENCES account_heading(id);

ALTER TABLE ONLY account
    ADD CONSTRAINT account_heading_negative_balance_fkey FOREIGN KEY (heading_negative_balance) REFERENCES account_heading(id);

-- account_link
ALTER TABLE ONLY account_link
    ADD CONSTRAINT account_link_account_id_fkey FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE;

ALTER TABLE ONLY account_link
    ADD CONSTRAINT account_link_description_fkey FOREIGN KEY (description) REFERENCES account_link_description(description);

-- country_tax_form
ALTER TABLE ONLY country_tax_form
    ADD CONSTRAINT country_tax_form_country_id_fkey FOREIGN KEY (country_id) REFERENCES country(id);

-- location
ALTER TABLE ONLY location
    ADD CONSTRAINT location_country_id_fkey FOREIGN KEY (country_id) REFERENCES country(id);

-- parts
ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_expense_accno_id_fkey FOREIGN KEY (expense_accno_id) REFERENCES account(id);

ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_income_accno_id_fkey FOREIGN KEY (income_accno_id) REFERENCES account(id);

ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_inventory_accno_id_fkey FOREIGN KEY (inventory_accno_id) REFERENCES account(id);

ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_partsgroup_id_fkey FOREIGN KEY (partsgroup_id) REFERENCES partsgroup(id);

ALTER TABLE ONLY parts
    ADD CONSTRAINT parts_returns_accno_id_fkey FOREIGN KEY (returns_accno_id) REFERENCES account(id);

-- partsgroup (self-referential)
ALTER TABLE ONLY partsgroup
    ADD CONSTRAINT partsgroup_parent_fkey FOREIGN KEY (parent) REFERENCES partsgroup(id);

-- lsmb_sequence
ALTER TABLE ONLY lsmb_sequence
    ADD CONSTRAINT lsmb_sequence_setting_key_fkey FOREIGN KEY (setting_key) REFERENCES defaults(setting_key);

-- entity
ALTER TABLE ONLY entity
    ADD CONSTRAINT entity_country_id_fkey FOREIGN KEY (country_id) REFERENCES country(id);

-- entity_employee
ALTER TABLE ONLY entity_employee
    ADD CONSTRAINT entity_employee_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) ON DELETE CASCADE;

ALTER TABLE ONLY entity_employee
    ADD CONSTRAINT entity_employee_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES entity(id);

-- person
ALTER TABLE ONLY person
    ADD CONSTRAINT person_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) ON DELETE CASCADE;

ALTER TABLE ONLY person
    ADD CONSTRAINT person_salutation_id_fkey FOREIGN KEY (salutation_id) REFERENCES salutation(id);

-- entity_bank_account
ALTER TABLE ONLY entity_bank_account
    ADD CONSTRAINT entity_bank_account_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) ON DELETE CASCADE;

-- company
ALTER TABLE ONLY company
    ADD CONSTRAINT company_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) ON DELETE CASCADE;

ALTER TABLE ONLY company
    ADD CONSTRAINT company_sic_code_fkey FOREIGN KEY (sic_code) REFERENCES sic(code);

-- entity_credit_account
ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_ar_ap_account_id_fkey FOREIGN KEY (ar_ap_account_id) REFERENCES account(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_bank_account_fkey FOREIGN KEY (bank_account) REFERENCES entity_bank_account(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_business_id_fkey FOREIGN KEY (business_id) REFERENCES business(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES account(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_curr_fkey FOREIGN KEY (curr) REFERENCES currency(curr);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_discount_account_id_fkey FOREIGN KEY (discount_account_id) REFERENCES account(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES entity_employee(entity_id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_entity_class_fkey FOREIGN KEY (entity_class) REFERENCES entity_class(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) ON DELETE CASCADE;

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_language_code_fkey FOREIGN KEY (language_code) REFERENCES language(code) ON DELETE SET DEFAULT;

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_pricegroup_id_fkey FOREIGN KEY (pricegroup_id) REFERENCES pricegroup(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_primary_contact_fkey FOREIGN KEY (primary_contact) REFERENCES person(id);

ALTER TABLE ONLY entity_credit_account
    ADD CONSTRAINT entity_credit_account_taxform_id_fkey FOREIGN KEY (taxform_id) REFERENCES country_tax_form(id);

-- users
ALTER TABLE ONLY users
    ADD CONSTRAINT users_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id);

-- session
ALTER TABLE ONLY session
    ADD CONSTRAINT session_users_id_fkey FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE;

-- transactions
ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES entity(id);

ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_entered_by_fkey FOREIGN KEY (entered_by) REFERENCES entity(id);

ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES session(session_id) ON DELETE SET NULL;

ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_trans_type_code_fkey FOREIGN KEY (trans_type_code) REFERENCES trans_type(code);

ALTER TABLE ONLY transactions
    ADD CONSTRAINT transactions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflow(workflow_id);

-- open_item
ALTER TABLE ONLY open_item
    ADD CONSTRAINT open_item_account_id_fkey FOREIGN KEY (account_id) REFERENCES account(id);

-- invoice
ALTER TABLE ONLY invoice
    ADD CONSTRAINT invoice_parts_id_fkey FOREIGN KEY (parts_id) REFERENCES parts(id);

ALTER TABLE ONLY invoice
    ADD CONSTRAINT invoice_trans_id_fkey FOREIGN KEY (trans_id) REFERENCES transactions(id);

-- gl
ALTER TABLE ONLY gl
    ADD CONSTRAINT gl_id_fkey FOREIGN KEY (id) REFERENCES transactions(id) ON DELETE CASCADE;

-- ar
ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_id_fkey FOREIGN KEY (trans_id) REFERENCES transactions(id) ON DELETE CASCADE;

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_curr_fkey FOREIGN KEY (curr) REFERENCES currency(curr);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_entity_credit_account_fkey FOREIGN KEY (entity_credit_account) REFERENCES entity_credit_account(id);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_language_code_fkey FOREIGN KEY (language_code) REFERENCES language(code);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_open_item_id_fkey FOREIGN KEY (open_item_id) REFERENCES open_item(id);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_person_id_fkey FOREIGN KEY (person_id) REFERENCES entity_employee(entity_id);

ALTER TABLE ONLY ar
    ADD CONSTRAINT ar_shipto_fkey FOREIGN KEY (shipto) REFERENCES location(id);

-- ap
ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_id_fkey FOREIGN KEY (trans_id) REFERENCES transactions(id) ON DELETE CASCADE;

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_curr_fkey FOREIGN KEY (curr) REFERENCES currency(curr);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_entity_credit_account_fkey FOREIGN KEY (entity_credit_account) REFERENCES entity_credit_account(id);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_language_code_fkey FOREIGN KEY (language_code) REFERENCES language(code);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_open_item_id_fkey FOREIGN KEY (open_item_id) REFERENCES open_item(id);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_person_id_fkey FOREIGN KEY (person_id) REFERENCES entity_employee(entity_id);

ALTER TABLE ONLY ap
    ADD CONSTRAINT ap_shipto_fkey FOREIGN KEY (shipto) REFERENCES location(id);

-- acc_trans
ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_chart_id_fkey FOREIGN KEY (chart_id) REFERENCES account(id);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_curr_fkey FOREIGN KEY (curr) REFERENCES currency(curr);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoice(id);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_open_item_id_fkey FOREIGN KEY (open_item_id) REFERENCES open_item(id);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_trans_id_fkey FOREIGN KEY (trans_id) REFERENCES transactions(id);

ALTER TABLE ONLY acc_trans
    ADD CONSTRAINT acc_trans_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES voucher(id);

-- batch
ALTER TABLE ONLY batch
    ADD CONSTRAINT batch_batch_class_id_fkey FOREIGN KEY (batch_class_id) REFERENCES batch_class(id);

ALTER TABLE ONLY batch
    ADD CONSTRAINT batch_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES entity_employee(entity_id);

ALTER TABLE ONLY batch
    ADD CONSTRAINT batch_created_by_fkey FOREIGN KEY (created_by) REFERENCES entity_employee(entity_id);

ALTER TABLE ONLY batch
    ADD CONSTRAINT batch_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES session(session_id) ON DELETE SET NULL;

-- voucher
ALTER TABLE ONLY voucher
    ADD CONSTRAINT voucher_trans_id_fkey FOREIGN KEY (trans_id) REFERENCES transactions(id);

ALTER TABLE ONLY voucher
    ADD CONSTRAINT voucher_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES batch(id);

ALTER TABLE ONLY voucher
    ADD CONSTRAINT voucher_batch_class_fkey FOREIGN KEY (batch_class) REFERENCES batch_class(id);

-- cr_report
ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_chart_id_fkey FOREIGN KEY (chart_id) REFERENCES account(id);

ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES entity(id);

ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES entity(id);

ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_entered_by_fkey FOREIGN KEY (entered_by) REFERENCES entity(id);

ALTER TABLE ONLY cr_report
    ADD CONSTRAINT cr_report_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflow(workflow_id);

-- cr_report_line
ALTER TABLE ONLY cr_report_line
    ADD CONSTRAINT cr_report_line_report_id_fkey FOREIGN KEY (report_id) REFERENCES cr_report(id);

ALTER TABLE ONLY cr_report_line
    ADD CONSTRAINT cr_report_line_user_fkey FOREIGN KEY ("user") REFERENCES entity(id);
