-- Spec references: R-0017 (IMP-PIP-024, §Domain Model Completeness), A-0017 (§Storage / Schema Changes).
--
-- V1.33 — Contact completeness: email + structured addresses + phones
--
-- Per R-0017 IMP-PIP-024, every contact in the Ledgius domain model
-- must carry email, at least one structured postal address (line_1 /
-- city / region / postcode / country), optional shipping address,
-- and at least one phone with type classification. These fields are
-- load-bearing for external-integration export compatibility
-- (R-0057 Xero export, future MYOB / QuickBooks export) and for core
-- accounting correctness (invoice correspondence, BAS reporting,
-- debtor / creditor management).
--
-- Design choice: rather than bolt string columns onto
-- entity_credit_account, this migration wires up the existing
-- LedgerSMB `location` table properly via a new link table
-- (supports multiple addresses per contact with class classification)
-- and introduces a `contact` table for emails + phones (supports
-- multiple values with type classification per Xero / MYOB / Xero API
-- requirements).
--
-- No trade-offs. No ad-hoc columns. Proper normalisation using the
-- tables LedgerSMB already provides.

-- =============================================================================
-- 1. Seed location_class with the classes Ledgius uses
-- =============================================================================
--
-- location_class is present but empty today. Seeds the two classes
-- Ledgius consumers care about: 'billing' (postal; default for
-- invoicing / correspondence) and 'shipping' (physical delivery
-- address). 'authoritative' flags the canonical version when a class
-- appears more than once in future.

INSERT INTO location_class (id, class, authoritative)
VALUES
    (1, 'billing', true),
    (2, 'shipping', true)
ON CONFLICT (id) DO UPDATE SET
    class = EXCLUDED.class,
    authoritative = EXCLUDED.authoritative;

COMMENT ON TABLE location_class IS
    'Classification of location records by purpose. Seeded in V1.33 with '
    '''billing'' (postal correspondence / invoicing default) and ''shipping'' '
    '(physical delivery). Additional classes may be added by future migrations.';

-- =============================================================================
-- 2. Link table: entity_credit_account ↔ location
-- =============================================================================

CREATE TABLE IF NOT EXISTS eca_to_location (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_credit_account_id INTEGER NOT NULL REFERENCES entity_credit_account(id) ON DELETE CASCADE,
    location_id              INTEGER NOT NULL REFERENCES location(id) ON DELETE RESTRICT,
    location_class_id        INTEGER NOT NULL REFERENCES location_class(id),
    is_primary               BOOLEAN NOT NULL DEFAULT false,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- At most one PRIMARY location of a given class per contact. The partial
-- unique index enforces "each contact has exactly one primary billing
-- address and one primary shipping address" without blocking secondary
-- addresses of the same class.
CREATE UNIQUE INDEX IF NOT EXISTS
    uq_eca_to_location_primary
    ON eca_to_location (entity_credit_account_id, location_class_id)
    WHERE is_primary = true;

-- Supports "list every address for this contact" and "find contacts
-- in this postcode" queries at tenant scale.
CREATE INDEX IF NOT EXISTS
    idx_eca_to_location_eca
    ON eca_to_location (entity_credit_account_id, location_class_id);

COMMENT ON TABLE eca_to_location IS
    'Link table binding entity_credit_account (customer/vendor) records to location '
    '(structured postal address) records with a class (billing / shipping / …) per R-0017 '
    'IMP-PIP-024. Supports multiple addresses per contact; is_primary plus a partial unique '
    'index enforces exactly one primary address per class per contact.';

COMMENT ON COLUMN eca_to_location.id IS 'Surrogate PK. Auto-generated.';
COMMENT ON COLUMN eca_to_location.entity_credit_account_id IS 'FK to the contact record (entity_credit_account.id).';
COMMENT ON COLUMN eca_to_location.location_id IS 'FK to the location record (address rows).';
COMMENT ON COLUMN eca_to_location.location_class_id IS 'FK to location_class — ''billing'' / ''shipping'' / future classes.';
COMMENT ON COLUMN eca_to_location.is_primary IS 'Primary location of this class for this contact. Used by default-address queries; partial unique index enforces single primary per (contact, class).';
COMMENT ON COLUMN eca_to_location.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN eca_to_location.updated_at IS 'Row last-modified timestamp.';

COMMENT ON INDEX uq_eca_to_location_primary IS
    'Partial unique index enforcing at most one primary location per (contact, class). '
    'Secondary locations of the same class remain allowed.';
COMMENT ON INDEX idx_eca_to_location_eca IS
    'Supports "list all addresses for contact X, class Y" queries — the common read pattern '
    'when rendering contact detail or preparing an export row.';

-- =============================================================================
-- 3. Contact table — emails + phones (and future contact channels)
-- =============================================================================

CREATE TABLE IF NOT EXISTS contact (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_credit_account_id INTEGER NOT NULL REFERENCES entity_credit_account(id) ON DELETE CASCADE,
    contact_class            TEXT NOT NULL,
    value                    TEXT NOT NULL,
    is_primary               BOOLEAN NOT NULL DEFAULT false,
    notes                    TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.constraint_column_usage
        WHERE table_name = 'contact' AND constraint_name = 'contact_class_check'
    ) THEN
        ALTER TABLE contact
            ADD CONSTRAINT contact_class_check
            CHECK (contact_class IN (
                'email',
                'phone_office',
                'phone_mobile',
                'phone_fax',
                'phone_other',
                'website',
                'other'
            ));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.constraint_column_usage
        WHERE table_name = 'contact' AND constraint_name = 'contact_value_not_blank'
    ) THEN
        ALTER TABLE contact
            ADD CONSTRAINT contact_value_not_blank
            CHECK (length(trim(value)) > 0);
    END IF;
END $$;

-- Enforce exactly one primary email per contact and one primary phone
-- per class per contact. Secondary emails / phones allowed without
-- primary.
CREATE UNIQUE INDEX IF NOT EXISTS
    uq_contact_primary
    ON contact (entity_credit_account_id, contact_class)
    WHERE is_primary = true;

CREATE INDEX IF NOT EXISTS
    idx_contact_eca_class
    ON contact (entity_credit_account_id, contact_class);

-- Email-lookup index for "find contact by email" support queries.
CREATE INDEX IF NOT EXISTS
    idx_contact_email_value
    ON contact (lower(value))
    WHERE contact_class = 'email';

COMMENT ON TABLE contact IS
    'Contact channels (email, phone, fax, website) for an entity_credit_account record. Per '
    'R-0017 IMP-PIP-024 every contact carries at least one email (contact_class = ''email'') '
    'and at least one phone (contact_class starting ''phone_''). Multiple values allowed; '
    'is_primary plus partial unique index enforces single primary per (contact, class).';

COMMENT ON COLUMN contact.id IS 'Surrogate PK. Auto-generated.';
COMMENT ON COLUMN contact.entity_credit_account_id IS 'FK to the contact (customer/vendor) record.';
COMMENT ON COLUMN contact.contact_class IS 'Channel type: ''email'', ''phone_office'', ''phone_mobile'', ''phone_fax'', ''phone_other'', ''website'', ''other''. CHECK-constrained.';
COMMENT ON COLUMN contact.value IS 'The actual contact value (email address / phone number / URL). Trimmed of surrounding whitespace; CHECK enforces non-blank.';
COMMENT ON COLUMN contact.is_primary IS 'Marks this row as the primary value of its class for this contact. Exactly one primary per (contact, class) enforced by partial unique index.';
COMMENT ON COLUMN contact.notes IS 'Free-form notes about this contact channel (e.g. "reception only, use mobile outside hours").';
COMMENT ON COLUMN contact.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN contact.updated_at IS 'Row last-modified timestamp.';

COMMENT ON INDEX uq_contact_primary IS
    'Partial unique index enforcing at most one primary contact channel per (entity_credit_account, class). '
    'Allows multiple emails / phones per class with a designated primary.';
COMMENT ON INDEX idx_contact_eca_class IS
    'Supports "get all emails / phones for contact X" — the common read pattern when '
    'rendering contact detail or preparing an export row.';
COMMENT ON INDEX idx_contact_email_value IS
    'Case-insensitive partial index on email values for "which contact has this email" support '
    'queries. Only indexes rows where contact_class = ''email''.';
