-- Spec references: R-0065 (REC-021–024, REC-071–074), A-0036.
--
-- V1.40 — Reconciliation rule table
--
-- Rules match bank transaction descriptions and auto-apply or suggest
-- allocations. Tenant-wide (not per-bank-account). Manual rules
-- outrank smart-generated rules per REC-073 precedence tiebreak.

CREATE TABLE IF NOT EXISTS recon_rule (
    id                  SERIAL PRIMARY KEY,
    name                TEXT NOT NULL,
    match_pattern       TEXT NOT NULL,
    match_type          TEXT NOT NULL DEFAULT 'contains',
    default_account_id  INT REFERENCES account(id),
    default_tax_code_id INT REFERENCES tax_code(id),
    default_contact_id  INT,
    auto_apply          BOOLEAN NOT NULL DEFAULT false,
    is_split            BOOLEAN NOT NULL DEFAULT false,
    split_lines         JSONB,
    confidence          NUMERIC(3,2) NOT NULL DEFAULT 1.00,
    source              TEXT NOT NULL DEFAULT 'manual',
    use_count           INT NOT NULL DEFAULT 0,
    rejection_count     INT NOT NULL DEFAULT 0,
    name_override       TEXT,
    disabled            BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          TEXT
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.constraint_column_usage
        WHERE table_name = 'recon_rule' AND constraint_name = 'recon_rule_match_type_check'
    ) THEN
        ALTER TABLE recon_rule
            ADD CONSTRAINT recon_rule_match_type_check
            CHECK (match_type IN ('contains', 'exact', 'regex'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.constraint_column_usage
        WHERE table_name = 'recon_rule' AND constraint_name = 'recon_rule_source_check'
    ) THEN
        ALTER TABLE recon_rule
            ADD CONSTRAINT recon_rule_source_check
            CHECK (source IN ('manual', 'smart'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_recon_rule_active
    ON recon_rule (disabled, source, confidence DESC)
    WHERE disabled = false;

COMMENT ON TABLE recon_rule IS
    'Reconciliation rules that match bank transaction descriptions to GL accounts. '
    'Tenant-wide (REC-071). Manual rules outrank smart rules (REC-073).';
COMMENT ON COLUMN recon_rule.match_pattern IS 'Text pattern: substring for contains, exact string for exact, regex for regex.';
COMMENT ON COLUMN recon_rule.match_type IS 'How match_pattern is applied: contains (ILIKE), exact (=), regex (~*).';
COMMENT ON COLUMN recon_rule.auto_apply IS 'true = apply without user confirmation; false = show as suggestion only.';
COMMENT ON COLUMN recon_rule.is_split IS 'true = allocation uses split_lines JSONB; false = single-account allocation.';
COMMENT ON COLUMN recon_rule.split_lines IS 'JSONB array of split lines: [{account_id, percentage, description, tax_code_id}].';
COMMENT ON COLUMN recon_rule.confidence IS 'Confidence score 0.00-1.00. Increased by +0.10 per confirmation (REC-038a), decreased by -0.10 per 3 rejections (REC-038b).';
COMMENT ON COLUMN recon_rule.source IS 'manual = user-created; smart = generated by smart reconciliation engine.';
COMMENT ON COLUMN recon_rule.use_count IS 'Number of times this rule has been confirmed/applied.';
COMMENT ON COLUMN recon_rule.rejection_count IS 'Number of times a smart suggestion using this rule was rejected.';
COMMENT ON COLUMN recon_rule.name_override IS 'User-corrected meaningful name (REC-038c). Overrides extraction for this pattern.';
COMMENT ON COLUMN recon_rule.disabled IS 'Disabled rules excluded from matching but retained for audit (REC-074).';
